name: MOLECULE LINT

on:
  workflow_call:

jobs:
  yaml-lint:
    uses: buissetemmanuel/cicd-templates/.github/workflows/yamllint.yml@main
  ansible-lint:
    uses: buissetemmanuel/cicd-templates/.github/workflows/ansible-lint.yml@main
