name: MOLECULE TEST

'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  lint:
    uses: buissetemmanuel/github-actions-test/.github/workflows/molecule-lint.yml@main

  test:
    needs: lint
    uses: buissetemmanuel/cicd-templates/.github/workflows/molecule-test.yml@main
    strategy:
      matrix:
        distro:
          - fedora37
